[build-system]
requires = ["setuptools", "wheel", "cmake", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.macos]
# Build wheels for Python 3.8, 3.9, 3.10, and 3.11
build = "cp38-* cp39-* cp310-* cp311-*"
environment = {MACOSX_DEPLOYMENT_TARGET=11.0}
archs = ["x86_64", "universal2"]

[tool.cibuildwheel.linux]
# Build wheels for Linux only
build = "cp38-manylinux* cp39-manylinux* cp310-manylinux* cp311-manylinux*"
archs = ["x86_64"]
